name: deploy

on:
  push:
    branches: [master]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Install node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Install deps
        run: npm install

      - name: Build website
        run: |
          npm run build

      - name: Push website (branch)
        uses: jsmrcaga/action-netlify-deploy@master
        if: github.event_name == 'pull_request'
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_directory: dist

      - name: Push website (master)
        uses: jsmrcaga/action-netlify-deploy@master
        if: (github.event_name == 'push') && endsWith(github.ref, '/master')
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: dist
